mutation CreateTowRequest($userId: UUID!, $userLocationLatitude: Float!, $userLocationLongitude: Float!, $vehicleMake: String!, $vehicleModel: String!, $status: String!) @auth(level: USER) {
  towRequest_insert(data: {
    userId: $userId,
    userLocationLatitude: $userLocationLatitude,
    userLocationLongitude: $userLocationLongitude,
    vehicleMake: $vehicleMake,
    vehicleModel: $vehicleModel,
    status: $status
  })
}

query GetTowRequest($id: UUID!) @auth(level: USER) {
  towRequest(id: $id) {
    id
    userId
    userLocationLatitude
    userLocationLongitude
    vehicleMake
    vehicleModel
    status
    description
    operatorNotes
    destinationLocationLatitude
    destinationLocationLongitude
  }
}

mutation UpdateTowRequest($id: UUID!, $status: String, $operatorNotes: String, $operatorId: UUID) @auth(level: USER) {
  towRequest_update(
    id: $id,
    data: {
      status: $status,
      operatorNotes: $operatorNotes,
      operatorId: $operatorId
    }
  )
}

query ListAvailableOperators @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  operators(where: {isAvailable: {eq: true}}) {
    id
    displayName
    companyName
    vehicleType
    averageRating
    licensePlate
  }
}