import { UserRole, TruckOwner } from "./types";

export const CONSTANTINE_COORDS = { lat: 36.365, lng: 6.6147 };

export const TRANSLATIONS = {
  en: {
    welcome: "Welcome to DzTow",
    roleSelect: "Are you a Driver or a Tow Truck Owner?",
    driver: "Driver",
    owner: "Truck Owner",
    login: "Login",
    signup: "Sign Up",
    findingTrucks: "Finding nearby trucks...",
    requestTow: "Request Tow Truck",
    available: "Available",
    offline: "Offline",
    call: "Call",
    distance: "km away",
    status: "Status",
    cancel: "Cancel",
    resolve: "Resolved",
    language: "Language",
    profile: "Profile",
    dashboard: "Dashboard",
    truckType: "Truck Type",
    location: "Location",
    home: "Home",
    settings: "Settings",
    helpSupport: "Help & Support",
    logout: "Log Out",
    edit: "Edit",
    vehicle: "Vehicle",
    save: "Save",
    appTheme: "App Theme",
    primaryColor: "Primary Color",
    fontStyle: "Font Style",
    notifications: "Notifications",
    appInfo: "App Info",
    version: "Version",
    emailUs: "Email Us",
    callSupport: "Call Support",
    faq: "FAQ",
    faqs: [
      { q: "How do I request a tow truck?", a: "Go to the Home screen, confirm your location on the map, and tap the big red 'Request Tow Truck' button. Nearby drivers will be notified." },
      { q: "How is the price calculated?", a: "For this MVP version, prices are negotiated directly with the truck owner. We will add in-app estimates soon." },
      { q: "Can I cancel my request?", a: "Yes, you can cancel your request at any time from the home screen before the driver arrives." },
      { q: "Is this service available 24/7?", a: "It depends on the availability of independent truck owners in your area." }
    ],
    reportIssue: "Report an Issue",
    describeIssue: "Describe your issue...",
    submitReport: "Submit Report",
    availabilityStatus: "Availability Status",
    online: "Online",
    offlineStatus: "Offline",
    myTruck: "My Truck",
    plate: "Plate",
    serviceArea: "Service Area",
    truckBrand: "Truck Brand",
    brand: "Brand",
    required: "Required",
    truckList: "Truck List",
    chat: "Chat",
    typeMessage: "Type a message...",
    blockUser: "Block User",
    unblockUser: "Unblock User",
    muteChat: "Mute Chat",
    unmuteChat: "Unmute Chat",
    contacts: "Contacts",
    noMessages: "No messages yet. Start a conversation!",
    today: "Today",
    typing: "Typing...",
    showAll: "All",
    showOnline: "Online",
    showOffline: "Offline",
    verification: "Verification",
    enterOtp: "Please enter the verification code sent to your phone.",
    verify: "Verify",
    resendOtp: "Resend Code",
    driverAcceptedTitle: "Driver Accepted!",
    driverAcceptedBody: "A tow truck is on the way to your location.",
    newMessageTitle: "New Message",
    requestCreatedTitle: "Request Sent",
    requestCreatedBody: "Searching for nearby drivers...",
    enableNotifications: "Enable Notifications"
  },
  fr: {
    welcome: "Bienvenue sur DzTow",
    roleSelect: "Êtes-vous un conducteur ou un propriétaire de dépanneuse ?",
    driver: "Conducteur",
    owner: "Propriétaire",
    login: "Connexion",
    signup: "S'inscrire",
    findingTrucks: "Recherche de camions à proximité...",
    requestTow: "Demander une dépanneuse",
    available: "Disponible",
    offline: "Hors ligne",
    call: "Appeler",
    distance: "km",
    status: "Statut",
    cancel: "Annuler",
    resolve: "Résolu",
    language: "Langue",
    profile: "Profil",
    dashboard: "Tableau de bord",
    truckType: "Type de camion",
    location: "Emplacement",
    home: "Accueil",
    settings: "Paramètres",
    helpSupport: "Aide & Support",
    logout: "Se déconnecter",
    edit: "Modifier",
    vehicle: "Véhicule",
    save: "Enregistrer",
    appTheme: "Thème de l'application",
    primaryColor: "Couleur principale",
    fontStyle: "Style de police",
    notifications: "Notifications",
    appInfo: "Info App",
    version: "Version",
    emailUs: "Envoyez-nous un email",
    callSupport: "Appeler le support",
    faq: "FAQ",
    faqs: [
      { q: "Comment demander une dépanneuse ?", a: "Allez sur l'écran d'accueil, confirmez votre position sur la carte, et appuyez sur le grand bouton rouge 'Demander une dépanneuse'. Les dépanneurs à proximité seront notifiés." },
      { q: "Comment le prix est-il calculé ?", a: "Pour cette version MVP, les prix sont négociés directement avec le propriétaire de la dépanneuse. Nous ajouterons bientôt des estimations dans l'application." },
      { q: "Puis-je annuler ma demande ?", a: "Oui, vous pouvez annuler votre demande à tout moment depuis l'écran d'accueil avant l'arrivée du dépanneur." },
      { q: "Ce service est-il disponible 24h/24 et 7j/7 ?", a: "Cela dépend de la disponibilité des propriétaires de dépanneuses indépendants dans votre région." }
    ],
    reportIssue: "Signaler un problème",
    describeIssue: "Décrivez votre problème...",
    submitReport: "Soumettre",
    availabilityStatus: "Statut de disponibilité",
    online: "En ligne",
    offlineStatus: "Hors ligne",
    myTruck: "Mon Camion",
    plate: "Plaque",
    serviceArea: "Zone de service",
    truckBrand: "Marque du camion",
    brand: "Marque",
    required: "Requis",
    truckList: "Liste des camions",
    chat: "Messagerie",
    typeMessage: "Écrivez un message...",
    blockUser: "Bloquer l'utilisateur",
    unblockUser: "Débloquer",
    muteChat: "Mettre en sourdine",
    unmuteChat: "Réactiver les notifications",
    contacts: "Contacts",
    noMessages: "Pas encore de messages. Commencez une discussion !",
    today: "Aujourd'hui",
    typing: "Écrit...",
    showAll: "Tous",
    showOnline: "En ligne",
    showOffline: "Hors ligne",
    verification: "Vérification",
    enterOtp: "Veuillez entrer le code de vérification envoyé sur votre téléphone.",
    verify: "Vérifier",
    resendOtp: "Renvoyer le code",
    driverAcceptedTitle: "Chauffeur Accepté !",
    driverAcceptedBody: "Une dépanneuse est en route vers votre position.",
    newMessageTitle: "Nouveau Message",
    requestCreatedTitle: "Demande Envoyée",
    requestCreatedBody: "Recherche de chauffeurs à proximité...",
    enableNotifications: "Activer les notifications"
  },
  ar: {
    welcome: "مرحباً بكم في DzTow",
    roleSelect: "هل أنت سائق أم صاحب شاحنة جر؟",
    driver: "سائق",
    owner: "صاحب شاحنة",
    login: "دخول",
    signup: "تسجيل",
    findingTrucks: "جاري البحث عن شاحنات...",
    requestTow: "طلب شاحنة جر",
    available: "متاح",
    offline: "غير متصل",
    call: "اتصال",
    distance: "كم",
    status: "الحالة",
    cancel: "إلغاء",
    resolve: "تم الحل",
    language: "لغة",
    profile: "الملف الشخصي",
    dashboard: "لوحة التحكم",
    truckType: "نوع الشاحنة",
    location: "الموقع",
    home: "الرئيسية",
    settings: "الإعدادات",
    helpSupport: "المساعدة والدعم",
    logout: "تسجيل خروج",
    edit: "تعديل",
    vehicle: "المركبة",
    save: "حفظ",
    appTheme: "مظهر التطبيق",
    primaryColor: "اللون الرئيسي",
    fontStyle: "نمط الخط",
    notifications: "الإشعارات",
    appInfo: "معلومات التطبيق",
    version: "الإصدار",
    emailUs: "راسـلنا",
    callSupport: "اتصل بالدعم",
    faq: "الأسئلة الشائعة",
    faqs: [
      { q: "كيف أطلب شاحنة جر؟", a: "اذهب إلى الشاشة الرئيسية، قم بتأكيد موقعك على الخريطة، ثم اضغط على الزر الأحمر الكبير 'طلب شاحنة جر'. سيتم إشعار السائقين القريبين." },
      { q: "كيف يتم احتساب السعر؟", a: "في هذا الإصدار الأولي، يتم التفاوض على الأسعار مباشرة مع صاحب الشاحنة. سنضيف تقديرات الأسعار داخل التطبيق قريبًا." },
      { q: "هل يمكنني إلغاء طلبي؟", a: "نعم، يمكنك إلغاء طلبك في أي وقت من الشاشة الرئيسية قبل وصول السائق." },
      { q: "هل هذه الخدمة متاحة 24/7؟", a: "يعتمد ذلك على مدى توفر أصحاب الشاحنات المستقلين في منطقتك." }
    ],
    reportIssue: "الإبلاغ عن مشكلة",
    describeIssue: "صف المشكلة...",
    submitReport: "إرسال البلاغ",
    availabilityStatus: "حالة التوفر",
    online: "متصل",
    offlineStatus: "غير متصل",
    myTruck: "شاحنتي",
    plate: "اللوحة",
    serviceArea: "منطقة الخدمة",
    truckBrand: "علامة الشاحنة",
    brand: "العلامة",
    required: "مطلوب",
    truckList: "قائمة الشاحنات",
    chat: "الدردشة",
    typeMessage: "أكتب رسالة...",
    blockUser: "حظر المستخدم",
    unblockUser: "رفع الحظر",
    muteChat: "كتم الإشعارات",
    unmuteChat: "تفعيل الإشعارات",
    contacts: "جهات الاتصال",
    noMessages: "لا توجد رسائل. ابدأ المحادثة!",
    today: "اليوم",
    typing: "يكتب...",
    showAll: "الكل",
    showOnline: "متصل",
    showOffline: "غير متصل",
    verification: "التحقق",
    enterOtp: "يرجى إدخال رمز التحقق المرسل إلى هاتفك.",
    verify: "تحقق",
    resendOtp: "إعادة إرسال الرمز",
    driverAcceptedTitle: "تم قبول السائق!",
    driverAcceptedBody: "شاحنة جر في طريقها إليك.",
    newMessageTitle: "رسالة جديدة",
    requestCreatedTitle: "تم إرسال الطلب",
    requestCreatedBody: "جاري البحث عن سائقين قريبين...",
    enableNotifications: "تفعيل الإشعارات"
  }
};
