type User @table {
  displayName: String!
  phoneNumber: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
  defaultVehicleMake: String
  defaultVehicleModel: String
}

type Operator @table {
  displayName: String!
  phoneNumber: String!
  createdAt: Timestamp!
  vehicleType: String!
  licensePlate: String!
  email: String
  photoUrl: String
  companyName: String
  averageRating: Float
  isAvailable: Boolean
}

type TowRequest @table {
  user: User!
  operator: Operator
  userLocationLatitude: Float!
  userLocationLongitude: Float!
  vehicleMake: String!
  vehicleModel: String!
  createdAt: Timestamp!
  status: String!
  description: String
  destinationLocationLatitude: Float
  destinationLocationLongitude: Float
  operatorNotes: String
}

type Review @table {
  user: User!
  operator: Operator!
  towRequest: TowRequest!
  rating: Int!
  createdAt: Timestamp!
  comment: String
}